/**
 * This code is generated using [[https://www.scala-sbt.org/contraband/ sbt-contraband]].
 */

// DO NOT EDIT MANUALLY
package sbt.internal.langserver
/**
 * @param type The message type.
 * @param message The actual message
 * @param originId A unique identifier generated by the client to identify this request.
                   Can be omitted
 */
final class LogMessageParams private (
  val `type`: Long,
  val message: String,
  val originId: Option[String]) extends Serializable {
  
  
  
  override def equals(o: Any): Boolean = this.eq(o.asInstanceOf[AnyRef]) || (o match {
    case x: LogMessageParams => (this.`type` == x.`type`) && (this.message == x.message) && (this.originId == x.originId)
    case _ => false
  })
  override def hashCode: Int = {
    37 * (37 * (37 * (37 * (17 + "sbt.internal.langserver.LogMessageParams".##) + `type`.##) + message.##) + originId.##)
  }
  override def toString: String = {
    "LogMessageParams(" + `type` + ", " + message + ", " + originId + ")"
  }
  private[this] def copy(`type`: Long = `type`, message: String = message, originId: Option[String] = originId): LogMessageParams = {
    new LogMessageParams(`type`, message, originId)
  }
  def withType(`type`: Long): LogMessageParams = {
    copy(`type` = `type`)
  }
  def withMessage(message: String): LogMessageParams = {
    copy(message = message)
  }
  def withOriginId(originId: Option[String]): LogMessageParams = {
    copy(originId = originId)
  }
  def withOriginId(originId: String): LogMessageParams = {
    copy(originId = Option(originId))
  }
}
object LogMessageParams {
  
  def apply(`type`: Long, message: String, originId: Option[String]): LogMessageParams = new LogMessageParams(`type`, message, originId)
  def apply(`type`: Long, message: String, originId: String): LogMessageParams = new LogMessageParams(`type`, message, Option(originId))
}
